### ISSUE TITLE
Plugin uses deprecated Gradle `VersionNumber` API

### ISSUE THREAD

**Issue by ZacSweers** [bugsnag/bugsnag-android-gradle-plugin#498]
### Describe the bug
<img width="647" alt="image" src="https://user-images.githubusercontent.com/1361086/218291533-1ff8c841-9591-4e4b-a003-12a930d4a173.png">

This should be copied (or use `KotlinVersion` as a stand-in) rather than using the deprecated Gradle version

**Comment by johnkiely1** [comment]
Hey @ZacSweers, thanks, we are looking to get this addressed in the next major release, alongside adding support for AGP8.

**Comment by kenyee** [comment]
@johnkiely1 this bug appears to still exist:
https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/c6e0c7b10aa57dc75e50d53006f2d74a998c58c2/src/main/kotlin/com/bugsnag/android/gradle/internal/DexguardCompat.kt#L82

Will this plugin ever have a fix for this?  Or should people migrate to the new Gradle plugin?
https://docs.bugsnag.com/build-integrations/gradle-plugin/

**Comment by agrzegorzewski** [comment]
Hi @kenyee,

The BugSnag Android Gradle Plugin is not actively maintained anymore and we aim to deprecate it in favor of the BugSnag Gradle Plugin you’ve mentioned. [BugSnag docs › Build & deploy integrations › Gradle plugin](https://docs.bugsnag.com/build-integrations/gradle-plugin/) 

We’ve checked and the new plugin doesn’t use the deprecated VersionNumber API, so we’re closing this out now as that should resolve the issue.

Please let us know if you have any problems with the new plugin.
